name: MobileMels

on:
  workflow_dispatch:
  push:
    tags:
      - '**'
      
env:
  REGISTRY: "cristianmelsmobile"
  REGISTRY_SHORT_NAME: "cristianmelsmobile"
  IMAGE_NAME: "mobile:latest"
  IMAGE_SHORT_NAME: "mobile"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME) --no-cache -f ./Deploy/Dockerfile .
      - name: Docker Login and Docker Push
        run: |
          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
          docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME)

  deploy_copy_files:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - uses: actions/checkout@master
      - name: Copy File Via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          overwrite: true
          source: "Deploy/docker-compose.yml"
          target: "./"

  deploy:
    runs-on: ubuntu-latest
    needs: deploy_copy_files
    steps:
      - name: Droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA
          script: |
            docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
            docker-compose -f ./Deploy/docker-compose.yml down
            docker image rmi --force $(echo $REGISTRY)/$(echo $IMAGE_NAME)
            docker pull $(echo $REGISTRY)/$(echo $IMAGE_NAME)
            docker-compose -f ./Deploy/docker-compose.yml up -d --build